/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        PatientsMenu = new javax.swing.JMenu();
        addPatientsMenuItem = new javax.swing.JMenuItem();
        updateDeletePatients = new javax.swing.JMenuItem();
        PatientsListMenuItem = new javax.swing.JMenuItem();
        DoctorsMenu = new javax.swing.JMenu();
        addDoctorMenuItem = new javax.swing.JMenuItem();
        Doctors = new javax.swing.JMenuItem();
        DoctorsAllMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home - HMS");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Harrington", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Welcome to the Hospital Management System");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Hospital.jpg"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        PatientsMenu.setText("Patients");
        PatientsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientsMenuActionPerformed(evt);
            }
        });

        addPatientsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        addPatientsMenuItem.setText("Add Patients");
        addPatientsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientsMenuItemActionPerformed(evt);
            }
        });
        PatientsMenu.add(addPatientsMenuItem);

        updateDeletePatients.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        updateDeletePatients.setText("Update Or Delete Patients");
        updateDeletePatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDeletePatientsActionPerformed(evt);
            }
        });
        PatientsMenu.add(updateDeletePatients);

        PatientsListMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        PatientsListMenuItem.setText("All Patients");
        PatientsListMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientsListMenuItemActionPerformed(evt);
            }
        });
        PatientsMenu.add(PatientsListMenuItem);

        jMenuBar1.add(PatientsMenu);

        DoctorsMenu.setText("Doctors");

        addDoctorMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        addDoctorMenuItem.setText("Add Doctor");
        addDoctorMenuItem.setToolTipText("");
        addDoctorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDoctorMenuItemActionPerformed(evt);
            }
        });
        DoctorsMenu.add(addDoctorMenuItem);

        Doctors.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        Doctors.setText("Update Or Delete Doctors");
        Doctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorsActionPerformed(evt);
            }
        });
        DoctorsMenu.add(Doctors);

        DoctorsAllMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        DoctorsAllMenuItem.setText("Doctors List");
        DoctorsAllMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorsAllMenuItemActionPerformed(evt);
            }
        });
        DoctorsMenu.add(DoctorsAllMenuItem);

        jMenuBar1.add(DoctorsMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PatientsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientsMenuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_PatientsMenuActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jLabel2MouseClicked

    private void addPatientsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientsMenuItemActionPerformed
        // TODO add your handling code here:
        new View.AddPatient().setVisible(true);
        
    }//GEN-LAST:event_addPatientsMenuItemActionPerformed

    private void addDoctorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDoctorMenuItemActionPerformed
        // TODO add your handling code here:
        new View.AddDoctor().setVisible(true);
    }//GEN-LAST:event_addDoctorMenuItemActionPerformed

    private void DoctorsAllMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorsAllMenuItemActionPerformed
        // TODO add your handling code here:
        new View.doctorsList().setVisible(true);
    }//GEN-LAST:event_DoctorsAllMenuItemActionPerformed

    private void PatientsListMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientsListMenuItemActionPerformed
        // TODO add your handling code here:
        new View.PatientsList().setVisible(true);
    }//GEN-LAST:event_PatientsListMenuItemActionPerformed

    private void DoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorsActionPerformed
        // TODO add your handling code here:
        new View.UpdateDeleteDoctors().setVisible(true);
    }//GEN-LAST:event_DoctorsActionPerformed

    private void updateDeletePatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDeletePatientsActionPerformed
        // TODO add your handling code here:
        new View.UpdateDeletePatients().setVisible(true);
    }//GEN-LAST:event_updateDeletePatientsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Doctors;
    private javax.swing.JMenuItem DoctorsAllMenuItem;
    private javax.swing.JMenu DoctorsMenu;
    private javax.swing.JMenuItem PatientsListMenuItem;
    private javax.swing.JMenu PatientsMenu;
    private javax.swing.JMenuItem addDoctorMenuItem;
    private javax.swing.JMenuItem addPatientsMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem updateDeletePatients;
    // End of variables declaration//GEN-END:variables
}
